# Generated by Django 3.1.1 on 2020-09-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carlisting',
        ),
    ]
