# Generated by Django 3.1.1 on 2020-09-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0002_delete_carlisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carlisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=20)),
                ('engine_cc', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=20)),
                ('passenger_capacity', models.CharField(max_length=50)),
                ('gear', models.CharField(max_length=50)),
                ('manufacture_year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Car_image', models.ImageField(default=None, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
